---
# create some users
- name: create users
  hosts: all,!ml-demo-parent
  become: yes

  tasks:

    - name: create users
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /sbin/nologin
      with_items:
        - cpuhog
        - memstealer
        - networkguy
        - iouser
        - filestressor
        - randombadguy
