---
- name: tail Netdata collector log
  hosts: all
  become: yes
  vars_files:
    - ../../vars/netdata.yaml
  
  tasks:

    - name: retrieve collector log
      command: tail -n {{ netdata_collector_log_tail_lines | default(25) }} /var/log/netdata/collector.log
      register: tail_output

    - name: display log content
      debug:
        var: tail_output.stdout_lines
